-- Pokemon types + damage modifiers insert
-- Generated on 2026-03-28T03:36:03.801Z

INSERT INTO type (name, color) VALUES
  ('normal', '#A8A878'),
  ('fighting', '#C03028'),
  ('flying', '#A890F0'),
  ('poison', '#A040A0'),
  ('ground', '#E0C068'),
  ('rock', '#B8A038'),
  ('bug', '#A8B820'),
  ('ghost', '#705898'),
  ('steel', '#B8B8D0'),
  ('fire', '#F08030'),
  ('water', '#6890F0'),
  ('grass', '#78C850'),
  ('electric', '#F8D030'),
  ('psychic', '#F85888'),
  ('ice', '#98D8D8'),
  ('dragon', '#7038F8'),
  ('dark', '#705848'),
  ('fairy', '#EE99AC'),
  ('stellar', '#40B5A5');

INSERT INTO type_damage_modifier (modifier, attacking_type, defending_type) VALUES
  (0.5, (SELECT id FROM type WHERE name = 'normal'), (SELECT id FROM type WHERE name = 'rock')),
  (0.5, (SELECT id FROM type WHERE name = 'normal'), (SELECT id FROM type WHERE name = 'steel')),
  (0, (SELECT id FROM type WHERE name = 'normal'), (SELECT id FROM type WHERE name = 'ghost')),
  (2, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'normal')),
  (2, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'rock')),
  (2, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'steel')),
  (2, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'ice')),
  (2, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'dark')),
  (0.5, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'flying')),
  (0.5, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'poison')),
  (0.5, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'bug')),
  (0.5, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'psychic')),
  (0.5, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'fairy')),
  (0, (SELECT id FROM type WHERE name = 'fighting'), (SELECT id FROM type WHERE name = 'ghost')),
  (2, (SELECT id FROM type WHERE name = 'flying'), (SELECT id FROM type WHERE name = 'fighting')),
  (2, (SELECT id FROM type WHERE name = 'flying'), (SELECT id FROM type WHERE name = 'bug')),
  (2, (SELECT id FROM type WHERE name = 'flying'), (SELECT id FROM type WHERE name = 'grass')),
  (0.5, (SELECT id FROM type WHERE name = 'flying'), (SELECT id FROM type WHERE name = 'rock')),
  (0.5, (SELECT id FROM type WHERE name = 'flying'), (SELECT id FROM type WHERE name = 'steel')),
  (0.5, (SELECT id FROM type WHERE name = 'flying'), (SELECT id FROM type WHERE name = 'electric')),
  (2, (SELECT id FROM type WHERE name = 'poison'), (SELECT id FROM type WHERE name = 'grass')),
  (2, (SELECT id FROM type WHERE name = 'poison'), (SELECT id FROM type WHERE name = 'fairy')),
  (0.5, (SELECT id FROM type WHERE name = 'poison'), (SELECT id FROM type WHERE name = 'poison')),
  (0.5, (SELECT id FROM type WHERE name = 'poison'), (SELECT id FROM type WHERE name = 'ground')),
  (0.5, (SELECT id FROM type WHERE name = 'poison'), (SELECT id FROM type WHERE name = 'rock')),
  (0.5, (SELECT id FROM type WHERE name = 'poison'), (SELECT id FROM type WHERE name = 'ghost')),
  (0, (SELECT id FROM type WHERE name = 'poison'), (SELECT id FROM type WHERE name = 'steel')),
  (2, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'poison')),
  (2, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'rock')),
  (2, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'steel')),
  (2, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'fire')),
  (2, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'electric')),
  (0.5, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'bug')),
  (0.5, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'grass')),
  (0, (SELECT id FROM type WHERE name = 'ground'), (SELECT id FROM type WHERE name = 'flying')),
  (2, (SELECT id FROM type WHERE name = 'rock'), (SELECT id FROM type WHERE name = 'flying')),
  (2, (SELECT id FROM type WHERE name = 'rock'), (SELECT id FROM type WHERE name = 'bug')),
  (2, (SELECT id FROM type WHERE name = 'rock'), (SELECT id FROM type WHERE name = 'fire')),
  (2, (SELECT id FROM type WHERE name = 'rock'), (SELECT id FROM type WHERE name = 'ice')),
  (0.5, (SELECT id FROM type WHERE name = 'rock'), (SELECT id FROM type WHERE name = 'fighting')),
  (0.5, (SELECT id FROM type WHERE name = 'rock'), (SELECT id FROM type WHERE name = 'ground')),
  (0.5, (SELECT id FROM type WHERE name = 'rock'), (SELECT id FROM type WHERE name = 'steel')),
  (2, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'grass')),
  (2, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'psychic')),
  (2, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'dark')),
  (0.5, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'fighting')),
  (0.5, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'flying')),
  (0.5, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'poison')),
  (0.5, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'ghost')),
  (0.5, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'steel')),
  (0.5, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'fire')),
  (0.5, (SELECT id FROM type WHERE name = 'bug'), (SELECT id FROM type WHERE name = 'fairy')),
  (2, (SELECT id FROM type WHERE name = 'ghost'), (SELECT id FROM type WHERE name = 'ghost')),
  (2, (SELECT id FROM type WHERE name = 'ghost'), (SELECT id FROM type WHERE name = 'psychic')),
  (0.5, (SELECT id FROM type WHERE name = 'ghost'), (SELECT id FROM type WHERE name = 'dark')),
  (0, (SELECT id FROM type WHERE name = 'ghost'), (SELECT id FROM type WHERE name = 'normal')),
  (2, (SELECT id FROM type WHERE name = 'steel'), (SELECT id FROM type WHERE name = 'rock')),
  (2, (SELECT id FROM type WHERE name = 'steel'), (SELECT id FROM type WHERE name = 'ice')),
  (2, (SELECT id FROM type WHERE name = 'steel'), (SELECT id FROM type WHERE name = 'fairy')),
  (0.5, (SELECT id FROM type WHERE name = 'steel'), (SELECT id FROM type WHERE name = 'steel')),
  (0.5, (SELECT id FROM type WHERE name = 'steel'), (SELECT id FROM type WHERE name = 'fire')),
  (0.5, (SELECT id FROM type WHERE name = 'steel'), (SELECT id FROM type WHERE name = 'water')),
  (0.5, (SELECT id FROM type WHERE name = 'steel'), (SELECT id FROM type WHERE name = 'electric')),
  (2, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'bug')),
  (2, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'steel')),
  (2, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'grass')),
  (2, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'ice')),
  (0.5, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'rock')),
  (0.5, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'fire')),
  (0.5, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'water')),
  (0.5, (SELECT id FROM type WHERE name = 'fire'), (SELECT id FROM type WHERE name = 'dragon')),
  (2, (SELECT id FROM type WHERE name = 'water'), (SELECT id FROM type WHERE name = 'ground')),
  (2, (SELECT id FROM type WHERE name = 'water'), (SELECT id FROM type WHERE name = 'rock')),
  (2, (SELECT id FROM type WHERE name = 'water'), (SELECT id FROM type WHERE name = 'fire')),
  (0.5, (SELECT id FROM type WHERE name = 'water'), (SELECT id FROM type WHERE name = 'water')),
  (0.5, (SELECT id FROM type WHERE name = 'water'), (SELECT id FROM type WHERE name = 'grass')),
  (0.5, (SELECT id FROM type WHERE name = 'water'), (SELECT id FROM type WHERE name = 'dragon')),
  (2, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'ground')),
  (2, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'rock')),
  (2, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'water')),
  (0.5, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'flying')),
  (0.5, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'poison')),
  (0.5, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'bug')),
  (0.5, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'steel')),
  (0.5, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'fire')),
  (0.5, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'grass')),
  (0.5, (SELECT id FROM type WHERE name = 'grass'), (SELECT id FROM type WHERE name = 'dragon')),
  (2, (SELECT id FROM type WHERE name = 'electric'), (SELECT id FROM type WHERE name = 'flying')),
  (2, (SELECT id FROM type WHERE name = 'electric'), (SELECT id FROM type WHERE name = 'water')),
  (0.5, (SELECT id FROM type WHERE name = 'electric'), (SELECT id FROM type WHERE name = 'grass')),
  (0.5, (SELECT id FROM type WHERE name = 'electric'), (SELECT id FROM type WHERE name = 'electric')),
  (0.5, (SELECT id FROM type WHERE name = 'electric'), (SELECT id FROM type WHERE name = 'dragon')),
  (0, (SELECT id FROM type WHERE name = 'electric'), (SELECT id FROM type WHERE name = 'ground')),
  (2, (SELECT id FROM type WHERE name = 'psychic'), (SELECT id FROM type WHERE name = 'fighting')),
  (2, (SELECT id FROM type WHERE name = 'psychic'), (SELECT id FROM type WHERE name = 'poison')),
  (0.5, (SELECT id FROM type WHERE name = 'psychic'), (SELECT id FROM type WHERE name = 'steel')),
  (0.5, (SELECT id FROM type WHERE name = 'psychic'), (SELECT id FROM type WHERE name = 'psychic')),
  (0, (SELECT id FROM type WHERE name = 'psychic'), (SELECT id FROM type WHERE name = 'dark')),
  (2, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'flying')),
  (2, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'ground')),
  (2, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'grass')),
  (2, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'dragon')),
  (0.5, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'steel')),
  (0.5, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'fire')),
  (0.5, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'water')),
  (0.5, (SELECT id FROM type WHERE name = 'ice'), (SELECT id FROM type WHERE name = 'ice')),
  (2, (SELECT id FROM type WHERE name = 'dragon'), (SELECT id FROM type WHERE name = 'dragon')),
  (0.5, (SELECT id FROM type WHERE name = 'dragon'), (SELECT id FROM type WHERE name = 'steel')),
  (0, (SELECT id FROM type WHERE name = 'dragon'), (SELECT id FROM type WHERE name = 'fairy')),
  (2, (SELECT id FROM type WHERE name = 'dark'), (SELECT id FROM type WHERE name = 'ghost')),
  (2, (SELECT id FROM type WHERE name = 'dark'), (SELECT id FROM type WHERE name = 'psychic')),
  (0.5, (SELECT id FROM type WHERE name = 'dark'), (SELECT id FROM type WHERE name = 'fighting')),
  (0.5, (SELECT id FROM type WHERE name = 'dark'), (SELECT id FROM type WHERE name = 'dark')),
  (0.5, (SELECT id FROM type WHERE name = 'dark'), (SELECT id FROM type WHERE name = 'fairy')),
  (2, (SELECT id FROM type WHERE name = 'fairy'), (SELECT id FROM type WHERE name = 'fighting')),
  (2, (SELECT id FROM type WHERE name = 'fairy'), (SELECT id FROM type WHERE name = 'dragon')),
  (2, (SELECT id FROM type WHERE name = 'fairy'), (SELECT id FROM type WHERE name = 'dark')),
  (0.5, (SELECT id FROM type WHERE name = 'fairy'), (SELECT id FROM type WHERE name = 'poison')),
  (0.5, (SELECT id FROM type WHERE name = 'fairy'), (SELECT id FROM type WHERE name = 'steel')),
  (0.5, (SELECT id FROM type WHERE name = 'fairy'), (SELECT id FROM type WHERE name = 'fire'));
