import { useCallback, useEffect, useState } from "react";
import { type SelectedPokemon } from "../types/Pokemon.types";
import { toast } from "sonner";
import { PokemonSearch } from "../components/PokemonSearch";
import { type Pokemon } from "../lib/pokemon-api";
import { TeamBuilder } from "../components/TeamBuilder";
import { getPokecoachSuggestion } from "../lib/pokecoach-api";
import { getGames, type Game } from "../lib/game-api";


const Index = () => {

    const [team, setTeam] = useState<SelectedPokemon[]>([]);
    const [showPokemonSearch, setShowPokemonSearch] = useState(false);
    const [loadingSuggestion, setLoadingSuggestion] = useState(false);
    const [retryingSuggestionIndex, setRetryingSuggestionIndex] = useState<number | null>(null);
    const [previousPokecoachRecommendations, setPreviousPokecoachRecommendations] = useState<string[]>([]);
    const [games, setGames] = useState<Game[]>([]);
    const [selectedGameName, setSelectedGameName] = useState("");

    useEffect(() => {
        const loadGames = async () => {
            try {
                const availableGames = await getGames();
                setGames(availableGames);
            } catch (error) {
                const message = error instanceof Error ? error.message : "Failed to load games.";
                toast.error(message);
            }
        };

        loadGames();
    }, [setGames]);

    const addToTeam = useCallback(
        (pokemon: Pokemon) => {
            if (team.length >= 6) {
                toast.error("Team is full! Remove a Pokémon first.");
                return;
            }
            const teamPokemon: SelectedPokemon = {
                ...pokemon,
                moves: [],
                ability: null,
                isMega: false,
                pros: [],
                cons: [],
                isPokecoachSuggestion: false,
            };
            setTeam((prev) => [...prev, teamPokemon]);
            setShowPokemonSearch(false);
            toast.success(`${pokemon.name.replace(/\b\w/g, (c) => c.toUpperCase())} added to team!`);
        },
        [team.length]
    );

    const updateTeamMember = useCallback((updated: SelectedPokemon) => {
        setTeam((prev) =>
            // todo: use autogenerated UUID
            prev.map((p) => (p.id === updated.id ? updated : p))
        );
    }, [setTeam]);

    const removeFromTeam = useCallback((index: number) => {
        setTeam((prev) => prev.filter((_, i) => i !== index));
    }, [setTeam]);

    const onUsePokeCoach = useCallback(async () => {
        if (team.length >= 6) {
            toast.error("Team is full! Remove a Pokémon first.");
            return;
        }

        if (retryingSuggestionIndex !== null) {
            return;
        }

        setLoadingSuggestion(true);

        try {
            const suggestedPokemon = await getPokecoachSuggestion({
                team,
                game: selectedGameName || null,
            });
            const suggestedPokemonWithFlag: SelectedPokemon = {
                ...suggestedPokemon,
                isPokecoachSuggestion: true,
            };  
            setTeam((prev) => [...prev, suggestedPokemonWithFlag]);
            setPreviousPokecoachRecommendations((_) => [suggestedPokemon.name]);
            toast.success(`${suggestedPokemon.name.replace(/\b\w/g, (c) => c.toUpperCase())} suggested by PokéCoach!`);
        } catch (error) {
            const message = error instanceof Error ? error.message : "Failed to get PokéCoach suggestion.";
            toast.error(message);
        } finally {
            setLoadingSuggestion(false);
        }
    }, [team, selectedGameName, previousPokecoachRecommendations, retryingSuggestionIndex]);

    const onRetryPokeCoachSuggestion = useCallback(async (index: number) => {
        if (loadingSuggestion || retryingSuggestionIndex !== null) {
            return;
        }

        const pokemonToReplace = team[index];

        if (!pokemonToReplace?.isPokecoachSuggestion) {
            return;
        }

        setRetryingSuggestionIndex(index);

        const teamWithoutSuggestion = team.filter((_, teamIndex) => teamIndex !== index);
        const previouslyRecommendedPokemon = [...previousPokecoachRecommendations, pokemonToReplace.name];

        try {
            const suggestedPokemon = await getPokecoachSuggestion({
                team: teamWithoutSuggestion,
                game: selectedGameName || null,
                previouslyRecommendedPokemon,
            });
            const suggestedPokemonWithFlag: SelectedPokemon = {
                ...suggestedPokemon,
                isPokecoachSuggestion: true,
            };

            setTeam((prev) => prev.map((pokemon, teamIndex) => (
                teamIndex === index ? suggestedPokemonWithFlag : pokemon
            )));
            setPreviousPokecoachRecommendations((prev) => [...prev, pokemonToReplace.name]);
            toast.success(`${suggestedPokemon.name.replace(/\b\w/g, (c) => c.toUpperCase())} suggested by PokéCoach!`);
        } catch (error) {
            const message = error instanceof Error ? error.message : "Failed to retry PokéCoach suggestion.";
            toast.error(message);
        } finally {
            setRetryingSuggestionIndex(null);
        }
    }, [team, selectedGameName, previousPokecoachRecommendations, loadingSuggestion, retryingSuggestionIndex]);

    return (
        <div className="min-h-screen bg-background flex flex-col">
            <header className="border-b border-border px-6 py-4 flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center">
                    {/* <span className="font-display font-bold text-primary-foreground text-sm">P</span> */}
                </div>
                <h1 className="font-display text-2xl font-bold tracking-tight">
                    Poké<span className="text-accent">Coach</span>
                </h1>
            </header>
            <main className="flex-1 flex flex-col lg:flex-row gap-0 overflow-hidden">
                <section className="min-w-0 flex-1 p-6 flex flex-col overflow-hidden">
                    <TeamBuilder 
                        pokemons={team} 
                        onRemove={removeFromTeam} 
                        onUpdate={updateTeamMember} 
                        onAddPokemon={() => setShowPokemonSearch((prev) => !prev)}
                        canAddPokemon={team.length < 6}
                        onUsePokeCoach={onUsePokeCoach}
                        onRetryPokeCoachSuggestion={onRetryPokeCoachSuggestion}
                        isUsingPokeCoach={loadingSuggestion}
                        retryingSuggestionIndex={retryingSuggestionIndex}
                        showPokemonSearch={showPokemonSearch}
                        games={games}
                        selectedGameName={selectedGameName}
                        onSelectedGameNameChange={setSelectedGameName}
                    />
                </section>
                {showPokemonSearch && (
                    <section className="w-full border-t border-border p-6 lg:w-[28rem] lg:border-l lg:border-t-0 flex flex-col overflow-hidden">
                        <div className="h-full rounded-xl border border-border bg-card p-4 shadow-sm flex flex-col overflow-hidden">
                            <div className="mb-4 flex items-center justify-between gap-3">
                                <h2 className="font-display text-lg font-bold">Add Pokemon</h2>
                                <button
                                    type="button"
                                    onClick={() => setShowPokemonSearch(false)}
                                    className="text-sm font-display text-muted-foreground transition-colors hover:text-foreground"
                                >
                                    Close
                                </button>
                            </div>
                            <div className="min-h-0 flex-1 overflow-hidden">
                                <PokemonSearch
                                    onAdd={addToTeam}
                                    teamFull={team.length >= 6}
                                    gameName={selectedGameName || undefined}
                                />
                            </div>
                        </div>
                    </section>
                )}
            </main>
        </div>
    );
}

export default Index;
