import { useCallback, useState } from "react";
import { type SelectedPokemon } from "../types/Pokemon.types";
import { toast } from "sonner";
import { PokemonSearch } from "../components/PokemonSearch";
import { type Pokemon } from "../lib/pokemon-api";
import { TeamBuilder } from "../components/TeamBuilder";


const Index = () => {

    const [team, setTeam] = useState<SelectedPokemon[]>([]);


    const addToTeam = useCallback(
        (pokemon: Pokemon) => {
            if (team.length >= 6) {
                toast.error("Team is full! Remove a Pokémon first.");
                return;
            }
            const teamPokemon: SelectedPokemon = {
                ...pokemon,
                moves: [],
                ability: null,
            };
            setTeam((prev) => [...prev, teamPokemon]);
            toast.success(`${pokemon.name.replace(/\b\w/g, (c) => c.toUpperCase())} added to team!`);
        },
        [team.length]
    );

    const updateTeamMember = useCallback((updated: SelectedPokemon) => {
        setTeam((prev) =>
            // todo: use autogenerated UUID
            prev.map((p) => (p.id === updated.id ? updated : p))
        );
    }, [setTeam]);

    const removeFromTeam = useCallback((index: number) => {
        setTeam((prev) => prev.filter((_, i) => i !== index));
    }, [setTeam]);

    return (
        <div className="min-h-screen bg-background flex flex-col">
            <header className="border-b border-border px-6 py-4 flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center">
                    {/* <span className="font-display font-bold text-primary-foreground text-sm">P</span> */}
                </div>
                <h1 className="font-display text-2xl font-bold tracking-tight">
                    Poké<span className="text-accent">Coach</span>
                </h1>
            </header>
            <main className="flex-1 flex flex-col lg:flex-row gap-0 overflow-hidden">
                <section className="lg:w-1/2 border-r border-border p-6 flex flex-col overflow-hidden">
                    <PokemonSearch onAdd={addToTeam} teamFull={team.length >= 6} />
                </section>
                <section className="lg:w-1/2 p-6 flex flex-col overflow-hidden">
                    <TeamBuilder 
                        pokemons={team} 
                        onRemove={removeFromTeam} 
                        onUpdate={updateTeamMember} 
                    />
                </section>
            </main>
        </div>
    );
}

export default Index;