import { useCallback, useEffect, useMemo, useState } from "react";
import { type SelectedPokemon } from "../types/Pokemon.types";
import { toast } from "sonner";
import { PokemonSearch } from "../components/PokemonSearch";
import { type Pokemon } from "../lib/pokemon-api";
import { TeamBuilder } from "../components/TeamBuilder";
import { TeamBuilderContext } from "../components/TeamBuilderContext";
import { getMoveSuggestion, getPokecoachSuggestion } from "../lib/pokecoach-api";
import { getGames, type Game } from "../lib/game-api";


const Index = () => {

    const [selectedPokemons, setSelectedPokemons] = useState<SelectedPokemon[]>([]);
    const [showPokemonSearch, setShowPokemonSearch] = useState(false);
    const [loadingSuggestion, setLoadingSuggestion] = useState(false);
    const [retryingSuggestionIndex, setRetryingSuggestionIndex] = useState<number | null>(null);
    const [askingMoveSuggestionIndex, setAskingMoveSuggestionIndex] = useState<number | null>(null);
    const [previousPokecoachRecommendations, setPreviousPokecoachRecommendations] = useState<string[]>([]);
    const [games, setGames] = useState<Game[]>([]);
    const [selectedGameName, setSelectedGameName] = useState("");

    useEffect(() => {
        const loadGames = async () => {
            try {
                const availableGames = await getGames();
                setGames(availableGames);
            } catch (error) {
                const message = error instanceof Error ? error.message : "Failed to load games.";
                toast.error(message);
            }
        };
        loadGames();
    }, [setGames]);

    const addToTeam = useCallback(
        (pokemon: Pokemon) => {
            if (selectedPokemons.length >= 6) {
                toast.error("Team is full! Remove a Pokémon first.");
                return;
            }
            const teamPokemon: SelectedPokemon = {
                ...pokemon,
                moves: [],
                ability: null,
                pros: [],
                cons: [],
                isPokecoachSuggestion: false,
            };
            setSelectedPokemons((prev) => [...prev, teamPokemon]);
            setShowPokemonSearch(false);
            toast.success(`${pokemon.name.replace(/\b\w/g, (c) => c.toUpperCase())} added to team!`);
        },
        [selectedPokemons.length]
    );

    const updateTeamMember = useCallback((updated: SelectedPokemon) => {
        setSelectedPokemons((prev) =>
            // todo: use autogenerated UUID
            prev.map((p) => (p.id === updated.id ? updated : p))
        );
    }, [setSelectedPokemons]);

    const updateTeamMemberAtIndex = useCallback((index: number, updated: SelectedPokemon) => {
        setSelectedPokemons((prev) =>
            prev.map((pokemon, teamIndex) => (teamIndex === index ? updated : pokemon))
        );
    }, [setSelectedPokemons]);

    const removeFromTeam = useCallback((index: number) => {
        setSelectedPokemons((prev) => prev.filter((_, i) => i !== index));
    }, [setSelectedPokemons]);

    const onClickUsePokeCoach = useCallback(async () => {
        if (selectedPokemons.length >= 6) {
            toast.error("Team is full! Remove a Pokémon first.");
            return;
        }

        if (retryingSuggestionIndex !== null) {
            return;
        }

        setLoadingSuggestion(true);

        try {
            const suggestedPokemon = await getPokecoachSuggestion({
                team: selectedPokemons,
                game: selectedGameName || null,
            });
            const suggestedPokemonWithFlag: SelectedPokemon = {
                ...suggestedPokemon,
                isPokecoachSuggestion: true,
            };  
            setSelectedPokemons((prev) => [...prev, suggestedPokemonWithFlag]);
            setPreviousPokecoachRecommendations((_) => [suggestedPokemon.name]);
            toast.success(`${suggestedPokemon.name.replace(/\b\w/g, (c) => c.toUpperCase())} suggested by PokéCoach!`);
        } catch (error) {
            const message = error instanceof Error ? error.message : "Failed to get PokéCoach suggestion.";
            toast.error(message);
        } finally {
            setLoadingSuggestion(false);
        }
    }, [selectedPokemons, selectedGameName, previousPokecoachRecommendations, retryingSuggestionIndex]);

    const onAskPokeCoachForMove = useCallback(async (index: number) => {
        if (askingMoveSuggestionIndex !== null) {
            return;
        }

        console.log("Asking PokéCoach for move suggestion for ", selectedPokemons[index].name);
        const pokemonIdToAskForMove = selectedPokemons[index].id;
        setAskingMoveSuggestionIndex(index);

        try {
            const suggestedMove = await getMoveSuggestion({
                team: selectedPokemons,
                pokemonIdToAskForMove,
            });
            setSelectedPokemons((prev) => prev.map((pokemon, i) => (
                i === index ? { ...pokemon, moves: [...pokemon.moves, suggestedMove] } : pokemon
            )));
            toast.success(`Move suggestion for ${selectedPokemons[index].name}: ${suggestedMove.name}`);
        } catch (error) {
            const message = error instanceof Error ? error.message : "Failed to get move suggestion from PokéCoach.";
            toast.error(message);
        } finally {
            setAskingMoveSuggestionIndex(null);
        }

    }, [selectedPokemons, askingMoveSuggestionIndex]);

    const onRetryPokeCoachSuggestion = useCallback(async (index: number) => {
        if (loadingSuggestion || retryingSuggestionIndex !== null) {
            return;
        }

        const pokemonToReplace = selectedPokemons[index];

        if (!pokemonToReplace?.isPokecoachSuggestion) {
            return;
        }

        setRetryingSuggestionIndex(index);

        const teamWithoutSuggestion = selectedPokemons.filter((_, teamIndex) => teamIndex !== index);
        const previouslyRecommendedPokemon = [...previousPokecoachRecommendations, pokemonToReplace.name];

        try {
            const suggestedPokemon = await getPokecoachSuggestion({
                team: teamWithoutSuggestion,
                game: selectedGameName || null,
                previouslyRecommendedPokemon,
            });
            const suggestedPokemonWithFlag: SelectedPokemon = {
                ...suggestedPokemon,
                isPokecoachSuggestion: true,
            };

            setSelectedPokemons((prev) => prev.map((pokemon, teamIndex) => (
                teamIndex === index ? suggestedPokemonWithFlag : pokemon
            )));
            setPreviousPokecoachRecommendations((prev) => [...prev, pokemonToReplace.name]);
            toast.success(`${suggestedPokemon.name.replace(/\b\w/g, (c) => c.toUpperCase())} suggested by PokéCoach!`);
        } catch (error) {
            const message = error instanceof Error ? error.message : "Failed to retry PokéCoach suggestion.";
            toast.error(message);
        } finally {
            setRetryingSuggestionIndex(null);
        }
    }, [selectedPokemons, selectedGameName, previousPokecoachRecommendations, loadingSuggestion, retryingSuggestionIndex]);

    const teamBuilderContextValue = useMemo(() => ({
        selectedPokemons: selectedPokemons,
        onRemove: removeFromTeam,
        onUpdate: updateTeamMember,
        onUpdateAtIndex: updateTeamMemberAtIndex,
        onClickAddPokemon: () => setShowPokemonSearch((prev) => !prev),
        onClickUsePokeCoach,
        onRetryPokeCoachSuggestion,
        canAddPokemon: selectedPokemons.length < 6,
        isUsingPokeCoach: loadingSuggestion,
        retryingSuggestionIndex,
        askingMoveSuggestionIndex,
        showPokemonSearch,
        games,
        selectedGameName,
        onSelectedGameNameChange: setSelectedGameName,
        onAskPokeCoachForMove,
    }), [
        selectedPokemons,
        removeFromTeam,
        updateTeamMember,
        updateTeamMemberAtIndex,
        onClickUsePokeCoach,
        onRetryPokeCoachSuggestion,
        loadingSuggestion,
        retryingSuggestionIndex,
        askingMoveSuggestionIndex,
        showPokemonSearch,
        games,
        selectedGameName,
        onAskPokeCoachForMove,
    ]);

    return (
        <TeamBuilderContext.Provider value={teamBuilderContextValue}>
            <div className="min-h-screen bg-background flex flex-col">
                <header className="border-b border-border px-6 py-4 flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center">
                        {/* <span className="font-display font-bold text-primary-foreground text-sm">P</span> */}
                    </div>
                    <h1 className="font-display text-2xl font-bold tracking-tight">
                        Poké<span className="text-accent">Coach</span>
                    </h1>
                </header>
                <main className="flex-1 flex flex-col lg:flex-row gap-0 overflow-hidden">
                    {showPokemonSearch && (
                        <section className="w-full border-t border-border p-6 lg:w-[28rem] lg:border-l lg:border-t-0 flex flex-col overflow-hidden">
                            <div className="h-full rounded-xl border border-border bg-card p-4 shadow-sm flex flex-col overflow-hidden">
                                <div className="mb-4 flex items-center justify-between gap-3">
                                    <h2 className="font-display text-lg font-bold">Add Pokemon</h2>
                                    <button
                                        type="button"
                                        onClick={() => setShowPokemonSearch(false)}
                                        className="text-sm font-display text-muted-foreground transition-colors hover:text-foreground"
                                    >
                                        Close
                                    </button>
                                </div>
                                <div className="min-h-0 flex-1 overflow-hidden">
                                    <PokemonSearch
                                        onAdd={addToTeam}
                                        teamFull={selectedPokemons.length >= 6}
                                        gameName={selectedGameName || undefined}
                                    />
                                </div>
                            </div>
                        </section>
                    )}
                    <section className="min-w-0 flex-1 p-6 flex flex-col overflow-hidden">
                        <TeamBuilder />
                    </section>
                </main>
            </div>
        </TeamBuilderContext.Provider>
    );
}

export default Index;
